name: UHCDoDo
main: KaitoDoDo\UHC\UHC
author: KaitoDoDo
version: 2.1.0
api: 3.9.3​

commands:
    uhc:
        usage: /uhc <make>
        description: UHC-Commands
    uhcstart:
        usage: /uhcstart
        description: Force-UHC-start
